on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        elixir: [1.16.2]
        otp: [26.2.3]

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps and _build cache
      id: mix-deps
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: PLT Cache
      uses: actions/cache@v4
      id: plt-cache
      with:
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          path: |
            ./_plts/core

    - name: Fetch and Compile Dependencies
      if: steps.mix-deps.outputs.cache-hit != 'true'
      run: |
        mix deps.get
        mix deps.compile

    - name: Create PLTs
      if: steps.plt-cache.outputs.cache-hit != 'true'
      run: |
        mix dialyzer --plt

    - name: Run Checks
      env: 
        AZURE_SPEECH_KEY: A_VALID_KEY
      run: mix check

