on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Release Flow

jobs:
  release-please:
    strategy:
      matrix:
        elixir: [1.16.2]
        otp: [26.2.3]
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare Release"
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: elixir
          package-name: ex_azure_speech
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Fetch and Compile Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mix deps.get
          mix deps.compile
      
      - name: Publish to hex.pm
        if: ${{ steps.release.outputs.release_created }}
        run: HEX_API_KEY=${{ secrets.HEX_API_KEY }} mix hex.publish --yes
